trainer:
  target: semanticist.engine.diffusion_trainer.DiffusionTrainer
  params:
    num_epoch: 3000
    valid_size: 1024

    blr: 2.5e-5
    cosine_lr: True
    warmup_epochs: 5
    max_grad_norm: 1.0

    batch_size: 128
    grad_accum_steps: 1
    num_workers: 12
    pin_memory: True

    precision: "bf16"
    compile: True
    enable_ema: True

    # More frequent images than checkpoints (your preference)
    sample_every: 20000
    save_every: 8000

    eval_fid: False
    fid_every: 999999999
    test_num_slots: 8
    cfg: 1.0

    result_folder: "/home/eeshan/orcd/pool/image_gen_mit_preemptable/h200_${oc.env:SLURM_JOB_ID}"
    log_dir: "/home/eeshan/orcd/pool/image_gen_mit_preemptable/h200_${oc.env:SLURM_JOB_ID}/logs"

    model:
      target: semanticist.stage1.diffuse_slot.DiffuseSlot
      params:
        ckpt_path: "/home/eeshan/orcd/pool/image_gen_mit_preemptable/h200_7360503/models/step168000"
        eval_fid: False
        encoder: "vit_base_patch16"
        enc_img_size: 256
        enc_causal: True

        num_slots: 128
        slot_dim: 16
        norm_slots: True

        dit_model: "DiT-S-4"
        num_sampling_steps: "250"

        vae: "stabilityai/sd-vae-ft-ema"

        enable_nest: True
        enable_nest_after: 0

        nest_mode: "bimodal"
        nest_head_cutoff: 8
        nest_head_anchors: [1, 2, 4, 8]
        nest_p_full: 0.0
        nest_p_head: 1.0
        nest_p_head_late: null
        nest_p_head_late_start_epoch: 0

        prefix_loss_p: 0.3
        prefix_loss_lambda: 0.10
        prefix_loss_ks: [1, 2, 4, 8]
        prefix_loss_start_epoch: 0

        tail_block_norm: True
        tail_block_norm_after: 0

        use_repa: False

    dataset:
      target: semanticist.utils.datasets.ImageNet
      params:
        root: "/home/eeshan/orcd/scratch/looney_tunes256"
        split: train
        aug: randcrop
        img_size: 256

    test_dataset:
      target: semanticist.utils.datasets.ImageNet
      params:
        root: "/home/eeshan/orcd/scratch/looney_tunes256"
        split: val
        aug: centercrop
        img_size: 256